using SoloHero.Core.Config;
using UnityEngine;

namespace SoloHero.Game.Config
{
    [CreateAssetMenu(menuName = "SoloHero/Config/Balance")]
    public sealed class BalanceConfig : ScriptableObject
    {
        public double HP_BASE = 100;
        public double ATK_BASE = 10;
        public double DEF_BASE = 20;
        public double ATKSPD_BASE = 1.0;
        public double MOVE_SPEED = 2.0;
        public double ATTACK_RANGE = 1.6;
        public double BASIC_SKILL_MULT = 3.0;
        public int BASIC_SKILL_TARGETS = 3;
        public double BASIC_SKILL_RANGE = 2.4;
        public double CRIT_RATE_BASE = 5;
        public double CRIT_MULT = 1.5;
        public double DEF_REF_MULT = 3;
        public double LEVEL_HP_GAIN = 5;
        public double LEVEL_ATK_GAIN = 0.5;
        public double EXP_REQ_BASE = 200;
        public double EXP_REQ_GROWTH = 1.18;
        public double UPG_COST_GROWTH = 1.12;
        public double UPG_BASE_HP = 300;
        public double UPG_BASE_ATK = 450;
        public double UPG_BASE_DEF = 450;
        public double UPG_BASE_SPD = 600;
        public double UPG_STAT_MULT = 1.16;
        public double UPG_GAIN_SPD = 0.02;
        public int UPG_MAX_LEVEL_SPD = 100;
        public double UPG_FARM_EXPONENT = 1.31;
        public double ENEMY_HP_BASE = 90;
        public double ENEMY_HP_GROWTH = 1.14;
        public double ENEMY_ATK_BASE = 5;
        public double ENEMY_ATK_GROWTH = 1.14;
        public double ENEMY_DEF = 0;
        public double ENEMY_EXP_BASE = 5;
        public double ENEMY_EXP_GROWTH = 1.10;
        public float ENEMY_ATK_INTERVAL = 1.2f;
        public int SPAWN_WAVE_SIZE = 4;
        public float SPAWN_WAVE_GAP = 0.5f;
        public double SPAWN_WAVE_SPACING = 0.8;
        public int SPAWN_MAX_ALIVE = 4;
        public double SPAWN_OFFSET_X = 1.5;
        public int KILL_TARGET_NORMAL = 8;
        public double BOSS_HP_MULT = 10;
        public double BOSS_ATK_MULT = 1.1;
        public float BOSS_ATK_INTERVAL = 1.8f;
        public double BOSS_GOLD_MULT = 5.0;
        public double BOSS_EXP_MULT = 5.0;
        public int BOSS_TIME_LIMIT = 30;
        public float BOSS_INTRO_TIME = 1.5f;
        public double STAGE_GOLD_BASE = 50;
        public double STAGE_GOLD_GROWTH = 1.04;
        public int CHAPTER_CLEAR_GEM = 60;
        public int OFFLINE_CAP = 21600;
        public double OFFLINE_DIVISOR = 3000;
        public int OFFLINE_MIN_SECONDS = 60;
        public double OFFLINE_AD_MULT = 2.0;
        public double GACHA_COST_SINGLE = 500;
        public double GACHA_COST_TEN = 4500;
        public int GACHA_COST_TEN_GEM = 200;
        public int GEM_GOLD_PACK_COST = 50;
        public double GEM_GOLD_PACK_STAGES = 100;
        public double GACHA_RATE_C = 55;
        public double GACHA_RATE_R = 33;
        public double GACHA_RATE_E = 10;
        public double GACHA_RATE_L = 2;
        public int GACHA_PITY = 100;
        public bool GACHA_PITY_RESET_ON_LEGENDARY = true;
        public int TUTORIAL_FREE_PULLS = 1;
        public double TUTORIAL_GOLD = 1000;
        public int TUTORIAL_REWARD_STAGE = 2;
        public double REFUND_C = 50;
        public double REFUND_R = 200;
        public double REFUND_E = 800;
        public double REFUND_L = 3000;
        public double EQUIP_ENHANCE_GAIN = 0.1;
        public int EQUIP_MAX_LEVEL = 10;
        public int AD_OFFLINE_DAILY = 5;
        public int AD_GEM_DAILY = 5;
        public double AD_GEM_REWARD = 5;
        public int AD_BOOSTER_DAILY = 1;
        public double AD_BOOSTER_SECONDS = 600;
        public double AD_BOOSTER_GOLD_MULT = 2.0;
        public int SKILL_SLOT_COUNT = 6;
        public int SKILL_UNLOCK_LV_1 = 1;
        public int SKILL_UNLOCK_LV_2 = 5;
        public int SKILL_UNLOCK_LV_3 = 12;
        public int SKILL_UNLOCK_LV_4 = 20;
        public int SKILL_UNLOCK_LV_5 = 30;
        public int SKILL_UNLOCK_LV_6 = 45;
        public int SKILL_MAX_LEVEL = 10;
        public double SKILL_LEVEL_GAIN = 10;
        public double SKILL_UPG_BASE_C = 900;
        public double SKILL_UPG_BASE_R = 1500;
        public double SKILL_UPG_BASE_E = 2400;
        public double SKILL_UPG_BASE_L = 4000;
        public double SKILL_UPG_COST_GROWTH = 1.15;
        public float SKILL_SEQUENCE_GAP = 0.4f;
        public double SKILL_SUMMON_COST_SINGLE = 5000;
        public double SKILL_SUMMON_COST_TEN = 45000;
        public int SKILL_SUMMON_COST_TEN_GEM = 200;
        public double SKILL_REFUND_C = 500;
        public double SKILL_REFUND_R = 1500;
        public double SKILL_REFUND_E = 4000;
        public double SKILL_REFUND_L = 15000;
        public double SKILL_OWNED_ATK_C = 0.25;
        public double SKILL_OWNED_ATK_R = 0.5;
        public double SKILL_OWNED_ATK_E = 1;
        public double SKILL_OWNED_ATK_L = 2;
        public double SKILL_BOSS_STUN_MULT = 0.5;
        public double SKILL_SHATTER_MULT = 1.5;
        public double SKILL_IGNITE_MULT = 1.3;
        public double ATTENDANCE_GEM = 30;
        public double ATTENDANCE_GOLD_STAGES = 20;
        public double ATTENDANCE_DAY7_GEM = 150;
        public float SKILL_DOT_TICK = 0.5f;
        public int TALENT_POINTS_PER_LEVEL = 1;
        public int TALENT_TIER_STEP = 5;
        public int TALENT_RESET_GEM = 100;
        public int STAGES_PER_CHAPTER = 10;
        public int MVP_CHAPTERS = 5;
        public float STAGE_CLEAR_DELAY = 2f;
        public float STAGE_RETRY_DELAY = 3f;
        public float BOSS_FAIL_AUTO_RETREAT = 5f;
        public float DEATH_ANIM_TIME = 1f;
        public int FAIL_STREAK_STEP_DOWN = 1;
        public int PPU = 32;
        public int PIXEL_REF_WIDTH = 270;
        public int PIXEL_REF_HEIGHT = 480;
        public int BATTLE_VIEW_RATIO = 55;
        public int HERO_SCREEN_X = 30;
        public double SWORD_ATK_C = 1.10;
        public double SWORD_ATK_R = 1.30;
        public double SWORD_ATK_E = 1.70;
        public double SWORD_ATK_L = 2.40;
        public double HELM_DEF_C = 1.10;
        public double HELM_DEF_R = 1.25;
        public double HELM_DEF_E = 1.50;
        public double HELM_DEF_L = 2.00;
        public double ARMOR_HP_C = 1.10;
        public double ARMOR_HP_R = 1.25;
        public double ARMOR_HP_E = 1.50;
        public double ARMOR_HP_L = 2.00;
        public double BOOTS_ATKSPD_C = 0.03;
        public double BOOTS_ATKSPD_R = 0.08;
        public double BOOTS_ATKSPD_E = 0.15;
        public double BOOTS_ATKSPD_L = 0.25;
        public double BOOTS_CRIT_C = 1;
        public double BOOTS_CRIT_R = 3;
        public double BOOTS_CRIT_E = 6;
        public double BOOTS_CRIT_L = 10;
        public int SAVE_DEBOUNCE = 250;

        public BalanceValues ToValues()
        {
            return new BalanceValues
            {
                HP_BASE = HP_BASE,
                ATK_BASE = ATK_BASE,
                DEF_BASE = DEF_BASE,
                ATKSPD_BASE = ATKSPD_BASE,
                MOVE_SPEED = MOVE_SPEED,
                ATTACK_RANGE = ATTACK_RANGE,
                BASIC_SKILL_MULT = BASIC_SKILL_MULT,
                BASIC_SKILL_TARGETS = BASIC_SKILL_TARGETS,
                BASIC_SKILL_RANGE = BASIC_SKILL_RANGE,
                CRIT_RATE_BASE = CRIT_RATE_BASE,
                CRIT_MULT = CRIT_MULT,
                DEF_REF_MULT = DEF_REF_MULT,
                LEVEL_HP_GAIN = LEVEL_HP_GAIN,
                LEVEL_ATK_GAIN = LEVEL_ATK_GAIN,
                EXP_REQ_BASE = EXP_REQ_BASE,
                EXP_REQ_GROWTH = EXP_REQ_GROWTH,
                UPG_COST_GROWTH = UPG_COST_GROWTH,
                UPG_BASE_HP = UPG_BASE_HP,
                UPG_BASE_ATK = UPG_BASE_ATK,
                UPG_BASE_DEF = UPG_BASE_DEF,
                UPG_BASE_SPD = UPG_BASE_SPD,
                UPG_STAT_MULT = UPG_STAT_MULT,
                UPG_GAIN_SPD = UPG_GAIN_SPD,
                UPG_MAX_LEVEL_SPD = UPG_MAX_LEVEL_SPD,
                UPG_FARM_EXPONENT = UPG_FARM_EXPONENT,
                ENEMY_HP_BASE = ENEMY_HP_BASE,
                ENEMY_HP_GROWTH = ENEMY_HP_GROWTH,
                ENEMY_ATK_BASE = ENEMY_ATK_BASE,
                ENEMY_ATK_GROWTH = ENEMY_ATK_GROWTH,
                ENEMY_DEF = ENEMY_DEF,
                ENEMY_EXP_BASE = ENEMY_EXP_BASE,
                ENEMY_EXP_GROWTH = ENEMY_EXP_GROWTH,
                ENEMY_ATK_INTERVAL = ENEMY_ATK_INTERVAL,
                SPAWN_WAVE_SIZE = SPAWN_WAVE_SIZE,
                SPAWN_WAVE_GAP = SPAWN_WAVE_GAP,
                SPAWN_WAVE_SPACING = SPAWN_WAVE_SPACING,
                SPAWN_MAX_ALIVE = SPAWN_MAX_ALIVE,
                SPAWN_OFFSET_X = SPAWN_OFFSET_X,
                KILL_TARGET_NORMAL = KILL_TARGET_NORMAL,
                BOSS_HP_MULT = BOSS_HP_MULT,
                BOSS_ATK_MULT = BOSS_ATK_MULT,
                BOSS_ATK_INTERVAL = BOSS_ATK_INTERVAL,
                BOSS_GOLD_MULT = BOSS_GOLD_MULT,
                BOSS_EXP_MULT = BOSS_EXP_MULT,
                BOSS_TIME_LIMIT = BOSS_TIME_LIMIT,
                BOSS_INTRO_TIME = BOSS_INTRO_TIME,
                STAGE_GOLD_BASE = STAGE_GOLD_BASE,
                STAGE_GOLD_GROWTH = STAGE_GOLD_GROWTH,
                CHAPTER_CLEAR_GEM = CHAPTER_CLEAR_GEM,
                OFFLINE_CAP = OFFLINE_CAP,
                OFFLINE_DIVISOR = OFFLINE_DIVISOR,
                OFFLINE_MIN_SECONDS = OFFLINE_MIN_SECONDS,
                OFFLINE_AD_MULT = OFFLINE_AD_MULT,
                GACHA_COST_SINGLE = GACHA_COST_SINGLE,
                GACHA_COST_TEN = GACHA_COST_TEN,
                GACHA_COST_TEN_GEM = GACHA_COST_TEN_GEM,
                GEM_GOLD_PACK_COST = GEM_GOLD_PACK_COST,
                GEM_GOLD_PACK_STAGES = GEM_GOLD_PACK_STAGES,
                GACHA_RATE_C = GACHA_RATE_C,
                GACHA_RATE_R = GACHA_RATE_R,
                GACHA_RATE_E = GACHA_RATE_E,
                GACHA_RATE_L = GACHA_RATE_L,
                GACHA_PITY = GACHA_PITY,
                GACHA_PITY_RESET_ON_LEGENDARY = GACHA_PITY_RESET_ON_LEGENDARY,
                TUTORIAL_FREE_PULLS = TUTORIAL_FREE_PULLS,
                TUTORIAL_GOLD = TUTORIAL_GOLD,
                TUTORIAL_REWARD_STAGE = TUTORIAL_REWARD_STAGE,
                REFUND_C = REFUND_C,
                REFUND_R = REFUND_R,
                REFUND_E = REFUND_E,
                REFUND_L = REFUND_L,
                EQUIP_ENHANCE_GAIN = EQUIP_ENHANCE_GAIN,
                EQUIP_MAX_LEVEL = EQUIP_MAX_LEVEL,
                AD_OFFLINE_DAILY = AD_OFFLINE_DAILY,
                AD_GEM_DAILY = AD_GEM_DAILY,
                AD_GEM_REWARD = AD_GEM_REWARD,
                AD_BOOSTER_DAILY = AD_BOOSTER_DAILY,
                AD_BOOSTER_SECONDS = AD_BOOSTER_SECONDS,
                AD_BOOSTER_GOLD_MULT = AD_BOOSTER_GOLD_MULT,
                SKILL_SLOT_COUNT = SKILL_SLOT_COUNT,
                SKILL_UNLOCK_LV_1 = SKILL_UNLOCK_LV_1,
                SKILL_UNLOCK_LV_2 = SKILL_UNLOCK_LV_2,
                SKILL_UNLOCK_LV_3 = SKILL_UNLOCK_LV_3,
                SKILL_UNLOCK_LV_4 = SKILL_UNLOCK_LV_4,
                SKILL_UNLOCK_LV_5 = SKILL_UNLOCK_LV_5,
                SKILL_UNLOCK_LV_6 = SKILL_UNLOCK_LV_6,
                SKILL_MAX_LEVEL = SKILL_MAX_LEVEL,
                SKILL_LEVEL_GAIN = SKILL_LEVEL_GAIN,
                SKILL_UPG_BASE_C = SKILL_UPG_BASE_C,
                SKILL_UPG_BASE_R = SKILL_UPG_BASE_R,
                SKILL_UPG_BASE_E = SKILL_UPG_BASE_E,
                SKILL_UPG_BASE_L = SKILL_UPG_BASE_L,
                SKILL_UPG_COST_GROWTH = SKILL_UPG_COST_GROWTH,
                SKILL_SEQUENCE_GAP = SKILL_SEQUENCE_GAP,
                SKILL_SUMMON_COST_SINGLE = SKILL_SUMMON_COST_SINGLE,
                SKILL_SUMMON_COST_TEN = SKILL_SUMMON_COST_TEN,
                SKILL_SUMMON_COST_TEN_GEM = SKILL_SUMMON_COST_TEN_GEM,
                SKILL_REFUND_C = SKILL_REFUND_C,
                SKILL_REFUND_R = SKILL_REFUND_R,
                SKILL_REFUND_E = SKILL_REFUND_E,
                SKILL_REFUND_L = SKILL_REFUND_L,
                SKILL_OWNED_ATK_C = SKILL_OWNED_ATK_C,
                SKILL_OWNED_ATK_R = SKILL_OWNED_ATK_R,
                SKILL_OWNED_ATK_E = SKILL_OWNED_ATK_E,
                SKILL_OWNED_ATK_L = SKILL_OWNED_ATK_L,
                SKILL_BOSS_STUN_MULT = SKILL_BOSS_STUN_MULT,
                SKILL_SHATTER_MULT = SKILL_SHATTER_MULT,
                SKILL_IGNITE_MULT = SKILL_IGNITE_MULT,
                ATTENDANCE_GEM = ATTENDANCE_GEM,
                ATTENDANCE_GOLD_STAGES = ATTENDANCE_GOLD_STAGES,
                ATTENDANCE_DAY7_GEM = ATTENDANCE_DAY7_GEM,
                SKILL_DOT_TICK = SKILL_DOT_TICK,
                TALENT_POINTS_PER_LEVEL = TALENT_POINTS_PER_LEVEL,
                TALENT_TIER_STEP = TALENT_TIER_STEP,
                TALENT_RESET_GEM = TALENT_RESET_GEM,
                STAGES_PER_CHAPTER = STAGES_PER_CHAPTER,
                MVP_CHAPTERS = MVP_CHAPTERS,
                STAGE_CLEAR_DELAY = STAGE_CLEAR_DELAY,
                STAGE_RETRY_DELAY = STAGE_RETRY_DELAY,
                BOSS_FAIL_AUTO_RETREAT = BOSS_FAIL_AUTO_RETREAT,
                DEATH_ANIM_TIME = DEATH_ANIM_TIME,
                FAIL_STREAK_STEP_DOWN = FAIL_STREAK_STEP_DOWN,
                PPU = PPU,
                PIXEL_REF_WIDTH = PIXEL_REF_WIDTH,
                PIXEL_REF_HEIGHT = PIXEL_REF_HEIGHT,
                BATTLE_VIEW_RATIO = BATTLE_VIEW_RATIO,
                HERO_SCREEN_X = HERO_SCREEN_X,
                SWORD_ATK_C = SWORD_ATK_C,
                SWORD_ATK_R = SWORD_ATK_R,
                SWORD_ATK_E = SWORD_ATK_E,
                SWORD_ATK_L = SWORD_ATK_L,
                HELM_DEF_C = HELM_DEF_C,
                HELM_DEF_R = HELM_DEF_R,
                HELM_DEF_E = HELM_DEF_E,
                HELM_DEF_L = HELM_DEF_L,
                ARMOR_HP_C = ARMOR_HP_C,
                ARMOR_HP_R = ARMOR_HP_R,
                ARMOR_HP_E = ARMOR_HP_E,
                ARMOR_HP_L = ARMOR_HP_L,
                BOOTS_ATKSPD_C = BOOTS_ATKSPD_C,
                BOOTS_ATKSPD_R = BOOTS_ATKSPD_R,
                BOOTS_ATKSPD_E = BOOTS_ATKSPD_E,
                BOOTS_ATKSPD_L = BOOTS_ATKSPD_L,
                BOOTS_CRIT_C = BOOTS_CRIT_C,
                BOOTS_CRIT_R = BOOTS_CRIT_R,
                BOOTS_CRIT_E = BOOTS_CRIT_E,
                BOOTS_CRIT_L = BOOTS_CRIT_L,
                SAVE_DEBOUNCE = SAVE_DEBOUNCE
            };
        }
    }
}
