using SoloHero.Core.Config;
using UnityEngine;

namespace SoloHero.Game.Config
{
    [CreateAssetMenu(menuName = "SoloHero/Config/Balance")]
    public sealed class BalanceConfig : ScriptableObject
    {
        public double HP_BASE = 100;
        public double ATK_BASE = 10;
        public double DEF_BASE = 10;
        public double ATKSPD_BASE = 1.0;
        public double MOVE_SPEED = 2.0;
        public double ATTACK_RANGE = 1.6;
        public double CRIT_RATE_BASE = 5;
        public double CRIT_MULT = 1.5;
        public double DEF_REF_MULT = 8.0;
        public double LEVEL_HP_GAIN = 20;
        public double LEVEL_ATK_GAIN = 2;
        public double EXP_REQ_BASE = 50;
        public double EXP_REQ_GROWTH = 1.12;
        public double UPG_COST_GROWTH = 1.12;
        public double UPG_BASE_HP = 100;
        public double UPG_BASE_ATK = 150;
        public double UPG_BASE_DEF = 150;
        public double UPG_BASE_SPD = 200;
        public double UPG_STAT_MULT = 1.16;
        public double UPG_GAIN_SPD = 0.02;
        public int UPG_MAX_LEVEL_SPD = 100;
        public double UPG_FARM_EXPONENT = 1.31;
        public double ENEMY_HP_BASE = 30;
        public double ENEMY_HP_GROWTH = 1.10;
        public double ENEMY_ATK_BASE = 5;
        public double ENEMY_ATK_GROWTH = 1.10;
        public double ENEMY_DEF = 0;
        public double ENEMY_EXP_BASE = 5;
        public double ENEMY_EXP_GROWTH = 1.10;
        public float ENEMY_ATK_INTERVAL = 1.2f;
        public float SPAWN_INTERVAL = 0.8f;
        public int SPAWN_MAX_ALIVE = 4;
        public double SPAWN_OFFSET_X = 1.5;
        public int KILL_TARGET_NORMAL = 8;
        public double BOSS_HP_MULT = 15.0;
        public double BOSS_ATK_MULT = 1.5;
        public float BOSS_ATK_INTERVAL = 1.8f;
        public double BOSS_GOLD_MULT = 5.0;
        public double BOSS_EXP_MULT = 5.0;
        public int BOSS_TIME_LIMIT = 30;
        public float BOSS_INTRO_TIME = 1.5f;
        public double STAGE_GOLD_BASE = 50;
        public double STAGE_GOLD_GROWTH = 1.08;
        public int CHAPTER_CLEAR_GEM = 60;
        public int OFFLINE_CAP = 21600;
        public double OFFLINE_DIVISOR = 400;
        public int OFFLINE_MIN_SECONDS = 60;
        public double OFFLINE_AD_MULT = 2.0;
        public double GACHA_COST_SINGLE = 500;
        public double GACHA_COST_TEN = 4500;
        public int GACHA_COST_TEN_GEM = 200;
        public double GACHA_RATE_C = 55;
        public double GACHA_RATE_R = 33;
        public double GACHA_RATE_E = 10;
        public double GACHA_RATE_L = 2;
        public int GACHA_PITY = 100;
        public bool GACHA_PITY_RESET_ON_LEGENDARY = true;
        public double REFUND_C = 50;
        public double REFUND_R = 200;
        public double REFUND_E = 800;
        public double REFUND_L = 3000;
        public double SKILL_MULT_1 = 3.0;
        public double SKILL_MULT_2 = 2.0;
        public float SKILL_CD_1 = 6f;
        public float SKILL_CD_2 = 12f;
        public float SKILL_CD_3 = 20f;
        public int SKILL_UNLOCK_LV_1 = 1;
        public int SKILL_UNLOCK_LV_2 = 5;
        public int SKILL_UNLOCK_LV_3 = 12;
        public int SKILL_MAX_LEVEL = 10;
        public double SKILL_LEVEL_GAIN = 10;
        public double SKILL_UPG_BASE_1 = 300;
        public double SKILL_UPG_BASE_2 = 500;
        public double SKILL_UPG_BASE_3 = 800;
        public double SKILL_UPG_COST_GROWTH = 1.15;
        public float SKILL_SEQUENCE_GAP = 0.4f;
        public double WHIRLWIND_RANGE = 3.0;
        public int WHIRLWIND_MIN_TARGETS = 2;
        public double BATTLECRY_ATK_BUFF = 30;
        public float BATTLECRY_DURATION = 8f;
        public double BATTLECRY_HEAL = 15;
        public double BATTLECRY_HP_THRESHOLD = 60;
        public int STAGES_PER_CHAPTER = 10;
        public int MVP_CHAPTERS = 5;
        public float STAGE_CLEAR_DELAY = 2f;
        public float STAGE_RETRY_DELAY = 3f;
        public float DEATH_ANIM_TIME = 1f;
        public int FAIL_STREAK_PROMPT = 3;
        public int PPU = 32;
        public int PIXEL_REF_WIDTH = 270;
        public int PIXEL_REF_HEIGHT = 480;
        public int BATTLE_VIEW_RATIO = 55;
        public int HERO_SCREEN_X = 30;
        public int SAVE_DEBOUNCE = 250;

        public BalanceValues ToValues()
        {
            return new BalanceValues
            {
                HP_BASE = HP_BASE,
                ATK_BASE = ATK_BASE,
                DEF_BASE = DEF_BASE,
                ATKSPD_BASE = ATKSPD_BASE,
                MOVE_SPEED = MOVE_SPEED,
                ATTACK_RANGE = ATTACK_RANGE,
                CRIT_RATE_BASE = CRIT_RATE_BASE,
                CRIT_MULT = CRIT_MULT,
                DEF_REF_MULT = DEF_REF_MULT,
                LEVEL_HP_GAIN = LEVEL_HP_GAIN,
                LEVEL_ATK_GAIN = LEVEL_ATK_GAIN,
                EXP_REQ_BASE = EXP_REQ_BASE,
                EXP_REQ_GROWTH = EXP_REQ_GROWTH,
                UPG_COST_GROWTH = UPG_COST_GROWTH,
                UPG_BASE_HP = UPG_BASE_HP,
                UPG_BASE_ATK = UPG_BASE_ATK,
                UPG_BASE_DEF = UPG_BASE_DEF,
                UPG_BASE_SPD = UPG_BASE_SPD,
                UPG_STAT_MULT = UPG_STAT_MULT,
                UPG_GAIN_SPD = UPG_GAIN_SPD,
                UPG_MAX_LEVEL_SPD = UPG_MAX_LEVEL_SPD,
                UPG_FARM_EXPONENT = UPG_FARM_EXPONENT,
                ENEMY_HP_BASE = ENEMY_HP_BASE,
                ENEMY_HP_GROWTH = ENEMY_HP_GROWTH,
                ENEMY_ATK_BASE = ENEMY_ATK_BASE,
                ENEMY_ATK_GROWTH = ENEMY_ATK_GROWTH,
                ENEMY_DEF = ENEMY_DEF,
                ENEMY_EXP_BASE = ENEMY_EXP_BASE,
                ENEMY_EXP_GROWTH = ENEMY_EXP_GROWTH,
                ENEMY_ATK_INTERVAL = ENEMY_ATK_INTERVAL,
                SPAWN_INTERVAL = SPAWN_INTERVAL,
                SPAWN_MAX_ALIVE = SPAWN_MAX_ALIVE,
                SPAWN_OFFSET_X = SPAWN_OFFSET_X,
                KILL_TARGET_NORMAL = KILL_TARGET_NORMAL,
                BOSS_HP_MULT = BOSS_HP_MULT,
                BOSS_ATK_MULT = BOSS_ATK_MULT,
                BOSS_ATK_INTERVAL = BOSS_ATK_INTERVAL,
                BOSS_GOLD_MULT = BOSS_GOLD_MULT,
                BOSS_EXP_MULT = BOSS_EXP_MULT,
                BOSS_TIME_LIMIT = BOSS_TIME_LIMIT,
                BOSS_INTRO_TIME = BOSS_INTRO_TIME,
                STAGE_GOLD_BASE = STAGE_GOLD_BASE,
                STAGE_GOLD_GROWTH = STAGE_GOLD_GROWTH,
                CHAPTER_CLEAR_GEM = CHAPTER_CLEAR_GEM,
                OFFLINE_CAP = OFFLINE_CAP,
                OFFLINE_DIVISOR = OFFLINE_DIVISOR,
                OFFLINE_MIN_SECONDS = OFFLINE_MIN_SECONDS,
                OFFLINE_AD_MULT = OFFLINE_AD_MULT,
                GACHA_COST_SINGLE = GACHA_COST_SINGLE,
                GACHA_COST_TEN = GACHA_COST_TEN,
                GACHA_COST_TEN_GEM = GACHA_COST_TEN_GEM,
                GACHA_RATE_C = GACHA_RATE_C,
                GACHA_RATE_R = GACHA_RATE_R,
                GACHA_RATE_E = GACHA_RATE_E,
                GACHA_RATE_L = GACHA_RATE_L,
                GACHA_PITY = GACHA_PITY,
                GACHA_PITY_RESET_ON_LEGENDARY = GACHA_PITY_RESET_ON_LEGENDARY,
                REFUND_C = REFUND_C,
                REFUND_R = REFUND_R,
                REFUND_E = REFUND_E,
                REFUND_L = REFUND_L,
                SKILL_MULT_1 = SKILL_MULT_1,
                SKILL_MULT_2 = SKILL_MULT_2,
                SKILL_CD_1 = SKILL_CD_1,
                SKILL_CD_2 = SKILL_CD_2,
                SKILL_CD_3 = SKILL_CD_3,
                SKILL_UNLOCK_LV_1 = SKILL_UNLOCK_LV_1,
                SKILL_UNLOCK_LV_2 = SKILL_UNLOCK_LV_2,
                SKILL_UNLOCK_LV_3 = SKILL_UNLOCK_LV_3,
                SKILL_MAX_LEVEL = SKILL_MAX_LEVEL,
                SKILL_LEVEL_GAIN = SKILL_LEVEL_GAIN,
                SKILL_UPG_BASE_1 = SKILL_UPG_BASE_1,
                SKILL_UPG_BASE_2 = SKILL_UPG_BASE_2,
                SKILL_UPG_BASE_3 = SKILL_UPG_BASE_3,
                SKILL_UPG_COST_GROWTH = SKILL_UPG_COST_GROWTH,
                SKILL_SEQUENCE_GAP = SKILL_SEQUENCE_GAP,
                WHIRLWIND_RANGE = WHIRLWIND_RANGE,
                WHIRLWIND_MIN_TARGETS = WHIRLWIND_MIN_TARGETS,
                BATTLECRY_ATK_BUFF = BATTLECRY_ATK_BUFF,
                BATTLECRY_DURATION = BATTLECRY_DURATION,
                BATTLECRY_HEAL = BATTLECRY_HEAL,
                BATTLECRY_HP_THRESHOLD = BATTLECRY_HP_THRESHOLD,
                STAGES_PER_CHAPTER = STAGES_PER_CHAPTER,
                MVP_CHAPTERS = MVP_CHAPTERS,
                STAGE_CLEAR_DELAY = STAGE_CLEAR_DELAY,
                STAGE_RETRY_DELAY = STAGE_RETRY_DELAY,
                DEATH_ANIM_TIME = DEATH_ANIM_TIME,
                FAIL_STREAK_PROMPT = FAIL_STREAK_PROMPT,
                PPU = PPU,
                PIXEL_REF_WIDTH = PIXEL_REF_WIDTH,
                PIXEL_REF_HEIGHT = PIXEL_REF_HEIGHT,
                BATTLE_VIEW_RATIO = BATTLE_VIEW_RATIO,
                HERO_SCREEN_X = HERO_SCREEN_X,
                SAVE_DEBOUNCE = SAVE_DEBOUNCE
            };
        }
    }
}
